import test from 'node:test';
import assert from 'node:assert/strict';
import {Battle} from '../dist/engine.js';
import {DEITIES} from '../dist/data.js';
function running(map=0){const b=new Battle(map);b.status='fighting';b.activeWaves=[1];return b;}
test('each deity respects its own divine protection',()=>{for(const d of DEITIES){const b=running(),e=b.spawn({type:'yaksha',protection:d.id,waveId:1});const hp=e.hp;assert.equal(b.hit(e,100,d.id),false);assert.equal(e.hp,hp);}});
test('offerings cannot overspend, duplicate a plot or buy a fourth favour level',()=>{const b=new Battle();assert.ok(b.build(0,'agni'));assert.equal(b.build(0,'indra'),false);assert.ok(b.upgrade(0));assert.ok(b.upgrade(0));assert.equal(b.upgrade(0),false);b.offerings=0;assert.equal(b.build(1,'indra'),false);assert.ok(b.sell(0));assert.equal(b.offerings,Math.floor((90+105+180)*.85));});
test('Saraswati reveals and boosts but never damages',()=>{const b=running();b.build(0,'saraswati');const e=b.spawn({type:'shade',waveId:1},135),hp=e.hp;b.tick(.1);assert.ok(b.visible(e));assert.equal(e.hp,hp);b.build(1,'vayu');const s=b.shrines[1];s.cooldown=10;b.tick(.1);assert.ok(s.cooldown<9.9);});
test('Durga waits for a manual target, recharges, and respects visibility and protection',()=>{const b=running();b.build(0,'durga');const e=b.spawn({type:'boss',waveId:1},150),hp=e.hp;b.tick(.1);assert.equal(e.hp,hp);assert.ok(b.strike(0,e.id));assert.ok(e.hp<hp);assert.equal(b.strike(0,e.id),false);b.shrines[0].cooldown=0;e.protection='durga';assert.equal(b.strike(0,e.id),false);e.protection=null;e.hidden=true;assert.equal(b.strike(0,e.id),false);});
test('Agni burn persists outside range and refreshes without stacking',()=>{const b=running();b.build(0,'agni');const e=b.spawn({type:'boss',waveId:1},135);b.tick(.1);assert.ok(e.burnUntil>b.time);b.ignite(e,10,6);b.ignite(e,10,6);assert.equal(e.burnDamage,10);e.distance=700;const hp=e.hp;b.tick(.1);assert.ok(e.hp<hp);e.protection='agni';const protectedHp=e.hp;b.tick(.1);assert.equal(e.hp,protectedHp);});
test('Vayu delivers heavy damage without routinely delaying foes',()=>{const b=running();b.build(0,'vayu');const e=b.spawn({type:'rakshasa',waveId:1},135),hp=e.hp;b.tick(.1);assert.ok(hp-e.hp>40);assert.ok(e.distance>135);assert.equal(e.rootUntil,0);});
test('Prithvi cracks armour without freezing her target',()=>{const b=running();b.offerings=1000;b.build(0,'prithvi');b.upgrade(0);const e=b.spawn({type:'yaksha',waveId:1},135);b.tick(.1);assert.ok(e.crackUntil>b.time);assert.ok(e.distance>135);assert.equal(e.rootUntil,0);});
test('Vajraketu resumes after his short vulnerable pause',()=>{const b=running(),e=b.spawn({type:'boss',boon:'iron',waveId:1},100);b.time=7;b.tick(.1);assert.ok(e.stopped);const d=e.distance;b.time=10;b.tick(.1);assert.equal(e.stopped,false);assert.ok(e.distance>d);});
test('targeted interventions need a location and do not spend on cancelled aiming',()=>{for(const id of ['vayu','prithvi']){const b=running();b.build(0,id);b.meter=100;assert.equal(b.intervention(0),false);assert.equal(b.meter,100);assert.ok(b.intervention(0,{x:150,y:155}));assert.equal(b.meter,0);}});
test('barriers expire and bosses cannot be held indefinitely',()=>{const b=running();b.build(0,'prithvi');b.meter=100;const e=b.spawn({type:'boss',waveId:1},150);b.intervention(0,{x:150,y:155});for(let i=0;i<60;i++){b.tick(.1);b.animate(.1);}assert.equal(b.barriers.length,0);assert.ok(e.distance>200);});
test('map actions have cooldowns and optional escorts cannot be farmed',()=>{const b=running();b.spawn({type:'boss',waveId:1},0);assert.ok(b.useFeature());assert.equal(b.useFeature(),false);b.wave=2;assert.ok(b.sendEscort());assert.equal(b.sendEscort(),false);b.escort.distance=1;const gold=b.offerings;b.tick(.1);assert.equal(b.escort.state,'safe');assert.equal(b.offerings,gold+100);assert.equal(b.sendEscort(),false);});
test('early-wave reward and completion rewards are paid exactly once',()=>{const b=new Battle();b.startWave();b.queue=[];b.spawn({type:'yaksha',waveId:1});const before=b.offerings,reward=b.earlyReward();assert.ok(b.startWave(true));assert.equal(b.offerings,before+reward);b.queue=[];b.spawn({type:'yaksha',waveId:2});assert.equal(b.startWave(true),false);for(const e of b.enemies)e.hp=0;b.tick(.1);assert.deepEqual(b.completedWaves,[1,2]);const after=b.offerings;b.tick(.1);assert.equal(b.offerings,after);});
test('save and resume retain burns, cooldowns, escorts and overlapping waves',()=>{const b=new Battle(1);b.build(0,'agni');b.startWave();b.queue=[];b.spawn({type:'yaksha',waveId:1},135);b.startWave(true);b.sendEscort();b.tick(.1);const c=new Battle(1,b.snapshot());for(let i=0;i<50;i++){b.tick(.1);c.tick(.1);}assert.deepEqual(c.snapshot(),b.snapshot());});
test('difficulty changes composition and stats; blessings cannot be switched after building',()=>{const easy=new Battle(1,null,{difficulty:'easy'}),hard=new Battle(1,null,{difficulty:'difficult'});assert.ok(hard.spawn({type:'yaksha'}).hp>easy.spawn({type:'yaksha'}).hp);assert.ok(hard.waves[3].length>easy.waves[3].length);assert.ok(easy.setBlessing('reach'));easy.build(0,'vayu');assert.equal(easy.setBlessing('offering'),false);assert.equal(easy.setDifficulty('normal'),false);});
