import test from 'node:test';
import assert from 'node:assert/strict';
import {Battle} from '../dist/engine.js';
import {targetAvailability,briefingFor,CAST,victoryLine} from '../dist/experience.js';
test('Durga cannot enter aiming with no foe, only hidden foes, protection or an ended wave',()=>{const b=new Battle();b.build(0,'durga');assert.equal(targetAvailability(b,0).ok,false);b.status='fighting';assert.equal(targetAvailability(b,0).label,'No visible targets');const e=b.spawn({type:'shade',waveId:1});assert.equal(targetAvailability(b,0).ok,false);e.revealUntil=5;assert.ok(targetAvailability(b,0).ok);e.protection='durga';assert.equal(targetAvailability(b,0).ok,false);e.protection=null;b.status='planning';assert.equal(targetAvailability(b,0).label,'Waiting for the wave');b.status='won';assert.equal(targetAvailability(b,0).label,'Battle ended');});
test('Mira introduces herself once, with all four companions represented later',()=>{const b=new Battle(0,null,{encounter:0});assert.ok(briefingFor(b,{}).text.includes('I’m Mira'));assert.ok(!briefingFor(b,{metMira:true}).text.includes('I’m Mira'));const cast=new Set();for(let map=0;map<5;map++)for(let encounter=0;encounter<3;encounter++)cast.add(briefingFor(new Battle(map,null,{encounter}),{metMira:true}).speaker);assert.deepEqual([...cast].sort(),Object.keys(CAST).sort());});
test('approaches, escorts and bosses have different lengths; town lanes rejoin the sanctuary',()=>{for(let map=0;map<5;map++)assert.deepEqual([0,1,2].map(encounter=>new Battle(map,null,{encounter}).totalWaves),[4,6,8]);const b=new Battle(2,null,{encounter:0}),a=b.spawn({type:'asura',lane:0}),z=b.spawn({type:'asura',lane:1});assert.notDeepEqual(b.pos(a),b.pos(z));a.distance=z.distance=b.route.total;assert.deepEqual(b.pos(a),b.pos(z));});
test('Durga can interrupt Mahishasura’s charge or exploit his recovery',()=>{function setup(){const b=new Battle(2);b.status='fighting';b.activeWaves=[8];b.build(0,'durga');const e=b.spawn({type:'boss',boon:'mahisha',waveId:8},100);b.meter=100;b.intervention(0);return [b,e];}const [b,e]=setup();b.time=6;b.tick(.01);assert.ok(e.charging);const before=e.hp;b.strike(0,e.id);const damage=before-e.hp;assert.equal(e.charging,false);assert.ok(e.boonBroken);const [c,f]=setup();c.time=8;c.tick(.01);assert.ok(f.recovering);const hp=f.hp;c.strike(0,f.id);assert.ok(hp-f.hp>damage*1.5);});
test('reconciliation text reflects whether the river stone reached safety',()=>{const b=new Battle(1,null,{encounter:1});assert.ok(victoryLine(b).includes('has not reached'));b.escort.state='safe';assert.ok(victoryLine(b).includes('is returned'));});
