import test from 'node:test';
import assert from 'node:assert/strict';
import {Battle} from '../dist/engine.js';
import {introductions} from '../dist/campaign.js';
function boss(map,boon){const b=new Battle(map);b.status='fighting';b.wave=8;b.activeWaves=[8];return [b,b.spawn({type:'boss',boon,waveId:8},100)];}
test('Mahishasura needs an empowered Durga strike; then other shrines work',()=>{const [b,e]=boss(2,'mahisha');b.build(0,'durga');const hp=e.hp;b.hit(e,100,'indra');assert.equal(e.hp,hp);b.strike(0,e.id);assert.equal(e.hp,hp);b.meter=100;assert.ok(b.intervention(0));b.strike(0,e.id);assert.ok(e.boonBroken);const next=e.hp;b.hit(e,100,'indra');assert.ok(e.hp<next);});
test('Mahishasura preparation warns and supplies intervention charge',()=>{const b=new Battle(2);b.wave=7;assert.equal(b.startWave(),false);assert.ok(b.message.includes('Durga'));assert.ok(b.build(0,'durga'));assert.ok(b.startWave());assert.equal(b.meter,100);});
test('ready empowered strikes cannot consume another full meter',()=>{const [b]=boss(2,'mahisha');b.build(0,'durga');b.meter=100;b.intervention(0);b.meter=100;assert.equal(b.intervention(0),false);assert.equal(b.meter,100);});
test('Vritra grows bounded coils and only actual Indra hits break them',()=>{const [b,e]=boss(4,'vritra');b.build(10,'indra');b.time=7;b.tick(.01);assert.equal(e.coils,3);b.hit(e,10,'agni');assert.equal(e.coils,3);b.hit(e,10,'indra');assert.equal(e.coils,2);b.hit(e,10,'indra');assert.equal(e.coils,2);const c=new Battle(4,b.snapshot());assert.equal(c.enemies[0].coils,2);});
test('Kali suppresses new Raktabija echoes without erasing existing ones',()=>{const [b,e]=boss(3,'raktabija');b.hit(e,1,'agni');assert.equal(b.enemies.filter(e=>e.type==='seed').length,1);assert.ok(b.useFeature());assert.equal(b.useFeature(),false);b.time=4;b.hit(e,1,'agni');assert.equal(b.enemies.filter(e=>e.type==='seed').length,1);b.time=11;b.hit(e,1,'agni');assert.equal(b.enemies.filter(e=>e.type==='seed').length,2);const c=new Battle(3,b.snapshot());assert.equal(c.kaliReadyAt,18);});
test('Varuna washback is shared across shrines and Wet strengthens lightning',()=>{const b=new Battle();b.status='fighting';b.activeWaves=[1];b.build(0,'varuna');b.build(1,'varuna');const e=b.spawn({type:'boss',waveId:1},170);b.tick(.1);assert.ok(e.distance<170);assert.ok(e.wetUntil>b.time);const position=e.distance;b.shrines.forEach(s=>s.cooldown=0);b.tick(.1);assert.ok(e.distance>position);assert.ok(e.pushUntil>b.time);});
test('naga emergence, mist and reconciliation work; raider waves contain no asuras',()=>{const raid=new Battle(0,null,{encounter:0});assert.ok(raid.waves.flat().every(e=>['vanara','stone'].includes(e.type)));const b=new Battle(1,null,{encounter:1});b.status='fighting';b.activeWaves=[1];const e=b.spawn({type:'naga',emerge:.32,waveId:1});assert.equal(e.distance,b.route.total*.32);b.spawn({type:'venom',waveId:1},e.distance);b.tick(.1);assert.equal(b.visible(e),false);b.escort.state='safe';b.tick(.1);assert.ok(b.enemies.every(e=>!['naga','venom'].includes(e.type)));});
test('late escort dispatch is refused and no instant final-clear bonus is paid',()=>{const b=new Battle();b.status='fighting';b.wave=8;b.activeWaves=[];assert.equal(b.sendEscort(),false);b.escort={state:'travelling',distance:b.route.total-100,health:100,hurtAt:100};const gold=b.offerings;b.tick(.1);assert.equal(b.offerings,gold);});
test('new boss and elite introductions retain distinct names and artwork',()=>{const b=new Battle(2);const card=introductions(b.waves[7],2,[]).find(c=>c.type==='boss');assert.equal(card.name,'Mahishasura');assert.equal(card.atlas,'myth-bosses');const elite=new Battle(2,null,{encounter:1});assert.equal(introductions(elite.waves[4],2,[]).find(c=>c.elite).name,'Illusionist');});
